require('dotenv').config();

module.exports = {
  // API OniSaúde
  ONI_API_BASE_URL: process.env.ONI_API_BASE_URL,
  ONI_CONV_ANS: process.env.ONI_CONV_ANS,
  ONI_PLANO_ID: process.env.ONI_PLANO_ID,
  ONI_SUPER_ID: process.env.ONI_SUPER_ID,
  ONI_PROC_CONSULTA: process.env.ONI_PROC_CONSULTA,
  ONI_PROC_TELECONSULTA: process.env.ONI_PROC_TELECONSULTA,
  ONI_MUNIC_GOIANIA: process.env.ONI_MUNIC_GOIANIA,

  // WhatsApp
  WHATSAPP_SEND_URL: process.env.WHATSAPP_SEND_URL,

  // Redis
  REDIS_SESSION_TTL: 1800, // 30 minutos

  // Estados do fluxo
  ESTADOS: {
    INICIO: 'INICIO',
    IDENTIFICANDO_SERVICO: 'IDENTIFICANDO_SERVICO',
    IDENTIFICANDO_CIDADE: 'IDENTIFICANDO_CIDADE',
    BUSCANDO_ESPECIALIDADE: 'BUSCANDO_ESPECIALIDADE',
    ESCOLHENDO_OPCAO: 'ESCOLHENDO_OPCAO',
    LISTANDO_PROFISSIONAIS: 'LISTANDO_PROFISSIONAIS',
    LISTANDO_HORARIOS: 'LISTANDO_HORARIOS',
    AGUARDANDO_LOGIN: 'AGUARDANDO_LOGIN',
    VERIFICANDO_CADASTRO: 'VERIFICANDO_CADASTRO',
    CADASTRANDO: 'CADASTRANDO',
    ESCOLHENDO_PACIENTE: 'ESCOLHENDO_PACIENTE',
    VERIFICANDO_TERMOS: 'VERIFICANDO_TERMOS',
    VALIDANDO_AGENDAMENTO: 'VALIDANDO_AGENDAMENTO',
    CONFIRMANDO_AGENDAMENTO: 'CONFIRMANDO_AGENDAMENTO',
    EXAMES_BUSCANDO: 'EXAMES_BUSCANDO',
    EXAMES_CARRINHO: 'EXAMES_CARRINHO',
    EXAMES_FINALIZANDO: 'EXAMES_FINALIZANDO',
    AGUARDANDO_PAGAMENTO: 'AGUARDANDO_PAGAMENTO',
    CONCLUIDO: 'CONCLUIDO',
    RECUPERANDO_SENHA: 'RECUPERANDO_SENHA'
  },

  // Tipos de serviço
  TIPO_SERVICO: {
    CONSULTA: 'CONSULTA',
    TELECONSULTA: 'TELECONSULTA',
    EXAMES: 'EXAMES'
  }
};

